<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ValoresYSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $valores_y = [
            //GRUPO B 
            ['grupo' => 'B', 'altura_min' => 4, 'altura_max' => 4.5, 'valor_y' => 16],
            ['grupo' => 'B', 'altura_min' => 4.5, 'altura_max' => 5, 'valor_y' => 23],
            ['grupo' => 'B', 'altura_min' => 5, 'altura_max' => 5.5, 'valor_y' => 32],
            ['grupo' => 'B', 'altura_min' => 5.5, 'altura_max' => 6, 'valor_y' => 42],
            ['grupo' => 'B', 'altura_min' => 6, 'altura_max' => 6.5, 'valor_y' => 55],
            ['grupo' => 'B', 'altura_min' => 6.5, 'altura_max' => 7, 'valor_y' => 70],
            ['grupo' => 'B', 'altura_min' => 7, 'altura_max' => 7.5, 'valor_y' => 87],
            ['grupo' => 'B', 'altura_min' => 7.5, 'altura_max' => 8, 'valor_y' => 106],
            ['grupo' => 'B', 'altura_min' => 8, 'altura_max' => 8.5, 'valor_y' => 127],
            ['grupo' => 'B', 'altura_min' => 8.5, 'altura_max' => 9, 'valor_y' => 149],
            ['grupo' => 'B', 'altura_min' => 9, 'altura_max' => 9.5, 'valor_y' => 173],
            ['grupo' => 'B', 'altura_min' => 9.5, 'altura_max' => 10, 'valor_y' => 198],
            ['grupo' => 'B', 'altura_min' => 10, 'altura_max' => 10.5, 'valor_y' => 224],
            ['grupo' => 'B', 'altura_min' => 10.5, 'altura_max' => 11, 'valor_y' => 251],
            ['grupo' => 'B', 'altura_min' => 11, 'altura_max' => 11.5, 'valor_y' => 277],
            ['grupo' => 'B', 'altura_min' => 11.5, 'altura_max' => 12, 'valor_y' => 304],
            ['grupo' => 'B', 'altura_min' => 12, 'altura_max' => 12.5, 'valor_y' => 330],
            ['grupo' => 'B', 'altura_min' => 12.5, 'altura_max' => 13, 'valor_y' => 356],
            ['grupo' => 'B', 'altura_min' => 13, 'altura_max' => 13.5, 'valor_y' => 382],
            ['grupo' => 'B', 'altura_min' => 13.5, 'altura_max' => 14, 'valor_y' => 406],
            ['grupo' => 'B', 'altura_min' => 14, 'altura_max' => 14.5, 'valor_y' => 430],
            ['grupo' => 'B', 'altura_min' => 14.5, 'altura_max' => 15, 'valor_y' => 453],
            ['grupo' => 'B', 'altura_min' => 15, 'altura_max' => 15.5, 'valor_y' => 475],
            ['grupo' => 'B', 'altura_min' => 15.5, 'altura_max' => 16, 'valor_y' => 495],
            ['grupo' => 'B', 'altura_min' => 16, 'altura_max' => 16.5, 'valor_y' => 514],
            ['grupo' => 'B', 'altura_min' => 16.5, 'altura_max' => 17, 'valor_y' => 533],
            ['grupo' => 'B', 'altura_min' => 17, 'altura_max' => 17.5, 'valor_y' => 550],
            ['grupo' => 'B', 'altura_min' => 17.5, 'altura_max' => 18, 'valor_y' => 566],
            ['grupo' => 'B', 'altura_min' => 18, 'altura_max' => 18.5, 'valor_y' => 581],
            ['grupo' => 'B', 'altura_min' => 18.5, 'altura_max' => 19, 'valor_y' => 595],
            ['grupo' => 'B', 'altura_min' => 19, 'altura_max' => 19.5, 'valor_y' => 608],
            ['grupo' => 'B', 'altura_min' => 19.5, 'altura_max' => 20, 'valor_y' => 620],
            ['grupo' => 'B', 'altura_min' => 20, 'altura_max' => 20.5, 'valor_y' => 631],
            ['grupo' => 'B', 'altura_min' => 20.5, 'altura_max' => 21, 'valor_y' => 641],
            ['grupo' => 'B', 'altura_min' => 21, 'altura_max' => 21.5, 'valor_y' => 650],
            ['grupo' => 'B', 'altura_min' => 21.5, 'altura_max' => 22, 'valor_y' => 659],
            ['grupo' => 'B', 'altura_min' => 22, 'altura_max' => 22.5, 'valor_y' => 667],
            ['grupo' => 'B', 'altura_min' => 22.5, 'altura_max' => 23, 'valor_y' => 674],
            ['grupo' => 'B', 'altura_min' => 23, 'altura_max' => 23.5, 'valor_y' => 681],
            ['grupo' => 'B', 'altura_min' => 23.5, 'altura_max' => 24, 'valor_y' => 687],
            ['grupo' => 'B', 'altura_min' => 24, 'altura_max' => 24.5, 'valor_y' => 693],
            ['grupo' => 'B', 'altura_min' => 24.5, 'altura_max' => 25, 'valor_y' => 698],
            ['grupo' => 'B', 'altura_min' => 25, 'altura_max' => 25.5, 'valor_y' => 703],
            ['grupo' => 'B', 'altura_min' => 25.5, 'altura_max' => 26, 'valor_y' => 707],
            ['grupo' => 'B', 'altura_min' => 26, 'altura_max' => 26.5, 'valor_y' => 711],
            ['grupo' => 'B', 'altura_min' => 26.5, 'altura_max' => 27, 'valor_y' => 714],
            ['grupo' => 'B', 'altura_min' => 27, 'altura_max' => 27.5, 'valor_y' => 717],
            ['grupo' => 'B', 'altura_min' => 27.5, 'altura_max' => 28, 'valor_y' => 720],
            ['grupo' => 'B', 'altura_min' => 28, 'altura_max' => 28.5, 'valor_y' => 723],
            ['grupo' => 'B', 'altura_min' => 28.5, 'altura_max' => 29, 'valor_y' => 726],
            ['grupo' => 'B', 'altura_min' => 29, 'altura_max' => 29.5, 'valor_y' => 728],
            ['grupo' => 'B', 'altura_min' => 29.5, 'altura_max' => 30, 'valor_y' => 730],
            ['grupo' => 'B', 'altura_min' => 30, 'altura_max' => 30.5, 'valor_y' => 732],
            ['grupo' => 'B', 'altura_min' => 30.5, 'altura_max' => 31, 'valor_y' => 733],
            ['grupo' => 'B', 'altura_min' => 31, 'altura_max' => 31.5, 'valor_y' => 735],
            ['grupo' => 'B', 'altura_min' => 31.5, 'altura_max' => 32, 'valor_y' => 736],
            ['grupo' => 'B', 'altura_min' => 32, 'altura_max' => 32.5, 'valor_y' => 738],
            ['grupo' => 'B', 'altura_min' => 32.5, 'altura_max' => 33, 'valor_y' => 739],
            ['grupo' => 'B', 'altura_min' => 33, 'altura_max' => 33.5, 'valor_y' => 740],
            ['grupo' => 'B', 'altura_min' => 33.5, 'altura_max' => 34, 'valor_y' => 741],
            ['grupo' => 'B', 'altura_min' => 34, 'altura_max' => 34.5, 'valor_y' => 742],
            ['grupo' => 'B', 'altura_min' => 34.5, 'altura_max' => 35, 'valor_y' => 742],
            ['grupo' => 'B', 'altura_min' => 35, 'altura_max' => 35.5, 'valor_y' => 743],
            ['grupo' => 'B', 'altura_min' => 35.5, 'altura_max' => 36, 'valor_y' => 744],
            ['grupo' => 'B', 'altura_min' => 36, 'altura_max' => 36.5, 'valor_y' => 744],
            ['grupo' => 'B', 'altura_min' => 36.5, 'altura_max' => 37, 'valor_y' => 745],
            ['grupo' => 'B', 'altura_min' => 37, 'altura_max' => 37.5, 'valor_y' => 745],
            ['grupo' => 'B', 'altura_min' => 37.5, 'altura_max' => 38, 'valor_y' => 746],
            ['grupo' => 'B', 'altura_min' => 38, 'altura_max' => 38.5, 'valor_y' => 746],
            ['grupo' => 'B', 'altura_min' => 38.5, 'altura_max' => 39, 'valor_y' => 746],
            ['grupo' => 'B', 'altura_min' => 39, 'altura_max' => 39.5, 'valor_y' => 747],
            ['grupo' => 'B', 'altura_min' => 39.5, 'altura_max' => 40, 'valor_y' => 747],
            ['grupo' => 'B', 'altura_min' => 40, 'altura_max' => 40.5, 'valor_y' => 747],


            //GRUPO C
            
            ['grupo' => 'C', 'altura_min' => 4, 'altura_max' => 4.5, 'valor_y' => 10],
            ['grupo' => 'C', 'altura_min' => 4.5, 'altura_max' => 5, 'valor_y' => 14],
            ['grupo' => 'C', 'altura_min' => 5, 'altura_max' => 5.5, 'valor_y' => 19],
            ['grupo' => 'C', 'altura_min' => 5.5, 'altura_max' => 6, 'valor_y' => 25],
            ['grupo' => 'C', 'altura_min' => 6, 'altura_max' => 6.5, 'valor_y' => 32],
            ['grupo' => 'C', 'altura_min' => 6.5, 'altura_max' => 7, 'valor_y' => 40],
            ['grupo' => 'C', 'altura_min' => 7, 'altura_max' => 7.5, 'valor_y' => 50],
            ['grupo' => 'C', 'altura_min' => 7.5, 'altura_max' => 8, 'valor_y' => 61],
            ['grupo' => 'C', 'altura_min' => 8, 'altura_max' => 8.5, 'valor_y' => 73],
            ['grupo' => 'C', 'altura_min' => 8.5, 'altura_max' => 9, 'valor_y' => 87],
            ['grupo' => 'C', 'altura_min' => 9, 'altura_max' => 9.5, 'valor_y' => 102],
            ['grupo' => 'C', 'altura_min' => 9.5, 'altura_max' => 10, 'valor_y' => 119],
            ['grupo' => 'C', 'altura_min' => 10, 'altura_max' => 10.5, 'valor_y' => 136],
            ['grupo' => 'C', 'altura_min' => 10.5, 'altura_max' => 11, 'valor_y' => 154],
            ['grupo' => 'C', 'altura_min' => 11, 'altura_max' => 11.5, 'valor_y' => 173],
            ['grupo' => 'C', 'altura_min' => 11.5, 'altura_max' => 12, 'valor_y' => 193],
            ['grupo' => 'C', 'altura_min' => 12, 'altura_max' => 12.5, 'valor_y' => 214],
            ['grupo' => 'C', 'altura_min' => 12.5, 'altura_max' => 13, 'valor_y' => 235],
            ['grupo' => 'C', 'altura_min' => 13, 'altura_max' => 13.5, 'valor_y' => 256],
            ['grupo' => 'C', 'altura_min' => 13.5, 'altura_max' => 14, 'valor_y' => 277],
            ['grupo' => 'C', 'altura_min' => 14, 'altura_max' => 14.5, 'valor_y' => 299],
            ['grupo' => 'C', 'altura_min' => 14.5, 'altura_max' => 15, 'valor_y' => 320],
            ['grupo' => 'C', 'altura_min' => 15, 'altura_max' => 15.5, 'valor_y' => 341],
            ['grupo' => 'C', 'altura_min' => 15.5, 'altura_max' => 16, 'valor_y' => 361],
            ['grupo' => 'C', 'altura_min' => 16, 'altura_max' => 16.5, 'valor_y' => 382],
            ['grupo' => 'C', 'altura_min' => 16.5, 'altura_max' => 17, 'valor_y' => 401],
            ['grupo' => 'C', 'altura_min' => 17, 'altura_max' => 17.5, 'valor_y' => 420],
            ['grupo' => 'C', 'altura_min' => 17.5, 'altura_max' => 18, 'valor_y' => 439],
            ['grupo' => 'C', 'altura_min' => 18, 'altura_max' => 18.5, 'valor_y' => 457],
            ['grupo' => 'C', 'altura_min' => 18.5, 'altura_max' => 19, 'valor_y' => 474],
            ['grupo' => 'C', 'altura_min' => 19, 'altura_max' => 19.5, 'valor_y' => 491],
            ['grupo' => 'C', 'altura_min' => 19.5, 'altura_max' => 20, 'valor_y' => 506],
            ['grupo' => 'C', 'altura_min' => 20, 'altura_max' => 20.5, 'valor_y' => 521],
            ['grupo' => 'C', 'altura_min' => 20.5, 'altura_max' => 21, 'valor_y' => 536],
            ['grupo' => 'C', 'altura_min' => 21, 'altura_max' => 21.5, 'valor_y' => 549],
            ['grupo' => 'C', 'altura_min' => 21.5, 'altura_max' => 22, 'valor_y' => 562],
            ['grupo' => 'C', 'altura_min' => 22, 'altura_max' => 22.5, 'valor_y' => 575],
            ['grupo' => 'C', 'altura_min' => 22.5, 'altura_max' => 23, 'valor_y' => 586],
            ['grupo' => 'C', 'altura_min' => 23, 'altura_max' => 23.5, 'valor_y' =>597],
            ['grupo' => 'C', 'altura_min' => 23.5, 'altura_max' => 24, 'valor_y' => 607],
            ['grupo' => 'C', 'altura_min' => 24, 'altura_max' => 24.5, 'valor_y' => 617],
            ['grupo' => 'C', 'altura_min' => 24.5, 'altura_max' => 25, 'valor_y' => 626],
            ['grupo' => 'C', 'altura_min' => 25, 'altura_max' => 25.5, 'valor_y' => 634],
            ['grupo' => 'C', 'altura_min' => 25.5, 'altura_max' => 26, 'valor_y' => 642],
            ['grupo' => 'C', 'altura_min' => 26, 'altura_max' => 26.5, 'valor_y' => 650],
            ['grupo' => 'C', 'altura_min' => 26.5, 'altura_max' => 27, 'valor_y' => 657],
            ['grupo' => 'C', 'altura_min' => 27, 'altura_max' => 27.5, 'valor_y' => 663],
            ['grupo' => 'C', 'altura_min' => 27.5, 'altura_max' => 28, 'valor_y' => 670],
            ['grupo' => 'C', 'altura_min' => 28, 'altura_max' => 28.5, 'valor_y' => 675],
            ['grupo' => 'C', 'altura_min' => 28.5, 'altura_max' => 29, 'valor_y' => 681],
            ['grupo' => 'C', 'altura_min' => 29, 'altura_max' => 29.5, 'valor_y' => 686],
            ['grupo' => 'C', 'altura_min' => 29.5, 'altura_max' => 30, 'valor_y' => 690],
            ['grupo' => 'C', 'altura_min' => 30, 'altura_max' => 30.5, 'valor_y' => 694],
            ['grupo' => 'C', 'altura_min' => 30.5, 'altura_max' => 31, 'valor_y' => 698],
            ['grupo' => 'C', 'altura_min' => 31, 'altura_max' => 31.5, 'valor_y' => 702],
            ['grupo' => 'C', 'altura_min' => 31.5, 'altura_max' => 32, 'valor_y' => 706],
            ['grupo' => 'C', 'altura_min' => 32, 'altura_max' => 32.5, 'valor_y' => 709],
            ['grupo' => 'C', 'altura_min' => 32.5, 'altura_max' => 33, 'valor_y' => 712],
            ['grupo' => 'C', 'altura_min' => 33, 'altura_max' => 33.5, 'valor_y' => 715],
            ['grupo' => 'C', 'altura_min' => 33.5, 'altura_max' => 34, 'valor_y' => 717],
            ['grupo' => 'C', 'altura_min' => 34, 'altura_max' => 34.5, 'valor_y' => 720],
            ['grupo' => 'C', 'altura_min' => 34.5, 'altura_max' => 35, 'valor_y' => 722],
            ['grupo' => 'C', 'altura_min' => 35, 'altura_max' => 35.5, 'valor_y' => 724],
            ['grupo' => 'C', 'altura_min' => 35.5, 'altura_max' => 36, 'valor_y' => 726],
            ['grupo' => 'C', 'altura_min' => 36, 'altura_max' => 36.5, 'valor_y' => 728],
            ['grupo' => 'C', 'altura_min' => 36.5, 'altura_max' => 37, 'valor_y' => 729],
            ['grupo' => 'C', 'altura_min' => 37, 'altura_max' => 37.5, 'valor_y' => 731],
            ['grupo' => 'C', 'altura_min' => 37.5, 'altura_max' => 38, 'valor_y' => 732],
            ['grupo' => 'C', 'altura_min' => 38, 'altura_max' => 38.5, 'valor_y' => 734],
            ['grupo' => 'C', 'altura_min' => 38.5, 'altura_max' => 39, 'valor_y' => 735],
            ['grupo' => 'C', 'altura_min' => 39, 'altura_max' => 39.5, 'valor_y' => 736],
            ['grupo' => 'C', 'altura_min' => 39.5, 'altura_max' => 40, 'valor_y' => 737],
            ['grupo' => 'C', 'altura_min' => 40, 'altura_max' => 40.5, 'valor_y' => 738],

            //GRUPO D

            ['grupo' => 'D', 'altura_min' => 4, 'altura_max' => 4.5, 'valor_y' => 24],
            ['grupo' => 'D', 'altura_min' => 4.5, 'altura_max' => 5, 'valor_y' => 36],
            ['grupo' => 'D', 'altura_min' => 5, 'altura_max' => 5.5, 'valor_y' => 51],
            ['grupo' => 'D', 'altura_min' => 5.5, 'altura_max' => 6, 'valor_y' => 69],
            ['grupo' => 'D', 'altura_min' => 6, 'altura_max' => 6.5, 'valor_y' => 91],
            ['grupo' => 'D', 'altura_min' => 6.5, 'altura_max' => 7, 'valor_y' => 117],
            ['grupo' => 'D', 'altura_min' => 7, 'altura_max' => 7.5, 'valor_y' => 146],
            ['grupo' => 'D', 'altura_min' => 7.5, 'altura_max' => 8, 'valor_y' => 178],
            ['grupo' => 'D', 'altura_min' => 8, 'altura_max' => 8.5, 'valor_y' => 213],
            ['grupo' => 'D', 'altura_min' => 8.5, 'altura_max' => 9, 'valor_y' => 250],
            ['grupo' => 'D', 'altura_min' => 9, 'altura_max' => 9.5, 'valor_y' => 289],
            ['grupo' => 'D', 'altura_min' => 9.5, 'altura_max' => 10, 'valor_y' => 329],
            ['grupo' => 'D', 'altura_min' => 10, 'altura_max' => 10.5, 'valor_y' => 370],
            ['grupo' => 'D', 'altura_min' => 10.5, 'altura_max' => 11, 'valor_y' => 410],
            ['grupo' => 'D', 'altura_min' => 11, 'altura_max' => 11.5, 'valor_y' => 450],
            ['grupo' => 'D', 'altura_min' => 11.5, 'altura_max' => 12, 'valor_y' => 489],
            ['grupo' => 'D', 'altura_min' => 12, 'altura_max' => 12.5, 'valor_y' => 527],
            ['grupo' => 'D', 'altura_min' => 12.5, 'altura_max' => 13, 'valor_y' => 564],
            ['grupo' => 'D', 'altura_min' => 13, 'altura_max' => 13.5, 'valor_y' => 599],
            ['grupo' => 'D', 'altura_min' => 13.5, 'altura_max' => 14, 'valor_y' => 632],
            ['grupo' => 'D', 'altura_min' => 14, 'altura_max' => 14.5, 'valor_y' => 663],
            ['grupo' => 'D', 'altura_min' => 14.5, 'altura_max' => 15, 'valor_y' => 692],
            ['grupo' => 'D', 'altura_min' => 15, 'altura_max' => 15.5, 'valor_y' => 719],
            ['grupo' => 'D', 'altura_min' => 15.5, 'altura_max' => 16, 'valor_y' => 745],
            ['grupo' => 'D', 'altura_min' => 16, 'altura_max' => 16.5, 'valor_y' => 768],
            ['grupo' => 'D', 'altura_min' => 16.5, 'altura_max' => 17, 'valor_y' => 789],
            ['grupo' => 'D', 'altura_min' => 17, 'altura_max' => 17.5, 'valor_y' => 809],
            ['grupo' => 'D', 'altura_min' => 17.5, 'altura_max' => 18, 'valor_y' => 827],
            ['grupo' => 'D', 'altura_min' => 18, 'altura_max' => 18.5, 'valor_y' => 844],
            ['grupo' => 'D', 'altura_min' => 18.5, 'altura_max' => 19, 'valor_y' => 859],
            ['grupo' => 'D', 'altura_min' => 19, 'altura_max' => 19.5, 'valor_y' => 873],
            ['grupo' => 'D', 'altura_min' => 19.5, 'altura_max' => 20, 'valor_y' => 885],
            ['grupo' => 'D', 'altura_min' => 20, 'altura_max' => 20.5, 'valor_y' => 897],
            ['grupo' => 'D', 'altura_min' => 20.5, 'altura_max' => 21, 'valor_y' => 907],
            ['grupo' => 'D', 'altura_min' => 21, 'altura_max' => 21.5, 'valor_y' => 916],
            ['grupo' => 'D', 'altura_min' => 21.5, 'altura_max' => 22, 'valor_y' => 925],
            ['grupo' => 'D', 'altura_min' => 22, 'altura_max' => 22.5, 'valor_y' => 932],
            ['grupo' => 'D', 'altura_min' => 22.5, 'altura_max' => 23, 'valor_y' => 939],
            ['grupo' => 'D', 'altura_min' => 23, 'altura_max' => 23.5, 'valor_y' => 946],
            ['grupo' => 'D', 'altura_min' => 23.5, 'altura_max' => 24, 'valor_y' => 951],
            ['grupo' => 'D', 'altura_min' => 24, 'altura_max' => 24.5, 'valor_y' => 956],
            ['grupo' => 'D', 'altura_min' => 24.5, 'altura_max' => 25, 'valor_y' => 961],
            ['grupo' => 'D', 'altura_min' => 25, 'altura_max' => 25.5, 'valor_y' => 965],
            ['grupo' => 'D', 'altura_min' => 25.5, 'altura_max' => 26, 'valor_y' => 968],
            ['grupo' => 'D', 'altura_min' => 26, 'altura_max' => 26.5, 'valor_y' => 972],
            ['grupo' => 'D', 'altura_min' => 26.5, 'altura_max' => 27, 'valor_y' => 975],
            ['grupo' => 'D', 'altura_min' => 27, 'altura_max' => 27.5, 'valor_y' => 977],
            ['grupo' => 'D', 'altura_min' => 27.5, 'altura_max' => 28, 'valor_y' => 980],
            ['grupo' => 'D', 'altura_min' => 28, 'altura_max' => 28.5, 'valor_y' => 982],
            ['grupo' => 'D', 'altura_min' => 28.5, 'altura_max' => 29, 'valor_y' => 984],
            ['grupo' => 'D', 'altura_min' => 29, 'altura_max' => 29.5, 'valor_y' => 985],
            ['grupo' => 'D', 'altura_min' => 29.5, 'altura_max' => 30, 'valor_y' => 987],
            ['grupo' => 'D', 'altura_min' => 30, 'altura_max' => 30.5, 'valor_y' => 988],
            ['grupo' => 'D', 'altura_min' => 30.5, 'altura_max' => 31, 'valor_y' => 989],
            ['grupo' => 'D', 'altura_min' => 31, 'altura_max' => 31.5, 'valor_y' => 991],
            ['grupo' => 'D', 'altura_min' => 31.5, 'altura_max' => 32, 'valor_y' => 992],
            ['grupo' => 'D', 'altura_min' => 32, 'altura_max' => 32.5, 'valor_y' => 992],
            ['grupo' => 'D', 'altura_min' => 32.5, 'altura_max' => 33, 'valor_y' => 993],
            ['grupo' => 'D', 'altura_min' => 33, 'altura_max' => 33.5, 'valor_y' => 994],
            ['grupo' => 'D', 'altura_min' => 33.5, 'altura_max' => 34, 'valor_y' => 995],
            ['grupo' => 'D', 'altura_min' => 34, 'altura_max' => 34.5, 'valor_y' => 995],
            ['grupo' => 'D', 'altura_min' => 34.5, 'altura_max' => 35, 'valor_y' => 996],
            ['grupo' => 'D', 'altura_min' => 35, 'altura_max' => 35.5, 'valor_y' => 996],
            ['grupo' => 'D', 'altura_min' => 35.5, 'altura_max' => 36, 'valor_y' => 996],
            ['grupo' => 'D', 'altura_min' => 36, 'altura_max' => 36.5, 'valor_y' => 997],
            ['grupo' => 'D', 'altura_min' => 36.5, 'altura_max' => 37, 'valor_y' => 997],
            ['grupo' => 'D', 'altura_min' => 37, 'altura_max' => 37.5, 'valor_y' => 997],
            ['grupo' => 'D', 'altura_min' => 37.5, 'altura_max' => 38, 'valor_y' => 998],
            ['grupo' => 'D', 'altura_min' => 38, 'altura_max' => 38.5, 'valor_y' => 998],
            ['grupo' => 'D', 'altura_min' => 38.5, 'altura_max' => 39, 'valor_y' => 998],
            ['grupo' => 'D', 'altura_min' => 39, 'altura_max' => 39.5, 'valor_y' => 998],
            ['grupo' => 'D', 'altura_min' => 39.5, 'altura_max' => 40, 'valor_y' => 999],
            ['grupo' => 'D', 'altura_min' => 40, 'altura_max' => 40.5, 'valor_y' => 999],

            //GRUPO E
            ['grupo' => 'E', 'altura_min' => 4, 'altura_max' => 4.5, 'valor_y' => 14],
            ['grupo' => 'E', 'altura_min' => 4.5, 'altura_max' => 5, 'valor_y' => 20],
            ['grupo' => 'E', 'altura_min' => 5, 'altura_max' => 5.5, 'valor_y' => 28],
            ['grupo' => 'E', 'altura_min' => 5.5, 'altura_max' => 6, 'valor_y' => 37],
            ['grupo' => 'E', 'altura_min' => 6, 'altura_max' => 6.5, 'valor_y' => 48],
            ['grupo' => 'E', 'altura_min' => 6.5, 'altura_max' => 7, 'valor_y' => 62],
            ['grupo' => 'E', 'altura_min' => 7, 'altura_max' => 7.5, 'valor_y' => 78],
            ['grupo' => 'E', 'altura_min' => 7.5, 'altura_max' => 8, 'valor_y' => 96],
            ['grupo' => 'E', 'altura_min' => 8, 'altura_max' => 8.5, 'valor_y' => 116],
            ['grupo' => 'E', 'altura_min' => 8.5, 'altura_max' => 9, 'valor_y' => 138],
            ['grupo' => 'E', 'altura_min' => 9, 'altura_max' => 9.5, 'valor_y' => 163],
            ['grupo' => 'E', 'altura_min' => 9.5, 'altura_max' => 10, 'valor_y' => 189],
            ['grupo' => 'E', 'altura_min' => 10, 'altura_max' => 10.5, 'valor_y' => 217],
            ['grupo' => 'E', 'altura_min' => 10.5, 'altura_max' => 11, 'valor_y' => 248],
            ['grupo' => 'E', 'altura_min' => 11, 'altura_max' => 11.5, 'valor_y' => 276],
            ['grupo' => 'E', 'altura_min' => 11.5, 'altura_max' => 12, 'valor_y' => 307],
            ['grupo' => 'E', 'altura_min' => 12, 'altura_max' => 12.5, 'valor_y' => 338],
            ['grupo' => 'E', 'altura_min' => 12.5, 'altura_max' => 13, 'valor_y' => 370],
            ['grupo' => 'E', 'altura_min' => 13, 'altura_max' => 13.5, 'valor_y' => 401],
            ['grupo' => 'E', 'altura_min' => 13.5, 'altura_max' => 14, 'valor_y' => 433],
            ['grupo' => 'E', 'altura_min' => 14, 'altura_max' => 14.5, 'valor_y' => 464],
            ['grupo' => 'E', 'altura_min' => 14.5, 'altura_max' => 15, 'valor_y' => 494],
            ['grupo' => 'E', 'altura_min' => 15, 'altura_max' => 15.5, 'valor_y' => 524],
            ['grupo' => 'E', 'altura_min' => 15.5, 'altura_max' => 16, 'valor_y' => 552],
            ['grupo' => 'E', 'altura_min' => 16, 'altura_max' => 16.5, 'valor_y' => 580],
            ['grupo' => 'E', 'altura_min' => 16.5, 'altura_max' => 17, 'valor_y' => 607],
            ['grupo' => 'E', 'altura_min' => 17, 'altura_max' => 17.5, 'valor_y' => 632],
            ['grupo' => 'E', 'altura_min' => 17.5, 'altura_max' => 18, 'valor_y' => 657],
            ['grupo' => 'E', 'altura_min' => 18, 'altura_max' => 18.5, 'valor_y' => 680],
            ['grupo' => 'E', 'altura_min' => 18.5, 'altura_max' => 19, 'valor_y' => 702],
            ['grupo' => 'E', 'altura_min' => 19, 'altura_max' => 19.5, 'valor_y' => 723],
            ['grupo' => 'E', 'altura_min' => 19.5, 'altura_max' => 20, 'valor_y' => 743],
            ['grupo' => 'E', 'altura_min' => 20, 'altura_max' => 20.5, 'valor_y' => 761],
            ['grupo' => 'E', 'altura_min' => 20.5, 'altura_max' => 21, 'valor_y' => 779],
            ['grupo' => 'E', 'altura_min' => 21, 'altura_max' => 21.5, 'valor_y' => 795],
            ['grupo' => 'E', 'altura_min' => 21.5, 'altura_max' => 22, 'valor_y' => 810],
            ['grupo' => 'E', 'altura_min' => 22, 'altura_max' => 22.5, 'valor_y' => 824],
            ['grupo' => 'E', 'altura_min' => 22.5, 'altura_max' => 23, 'valor_y' => 838],
            ['grupo' => 'E', 'altura_min' => 23, 'altura_max' => 23.5, 'valor_y' => 850],
            ['grupo' => 'E', 'altura_min' => 23.5, 'altura_max' => 24, 'valor_y' => 861],
            ['grupo' => 'E', 'altura_min' => 24, 'altura_max' => 24.5, 'valor_y' => 872],
            ['grupo' => 'E', 'altura_min' => 24.5, 'altura_max' => 25, 'valor_y' => 882],
            ['grupo' => 'E', 'altura_min' => 25, 'altura_max' => 25.5, 'valor_y' => 891],
            ['grupo' => 'E', 'altura_min' => 25.5, 'altura_max' => 26, 'valor_y' => 900],
            ['grupo' => 'E', 'altura_min' => 26, 'altura_max' => 26.5, 'valor_y' => 908],
            ['grupo' => 'E', 'altura_min' => 26.5, 'altura_max' => 27, 'valor_y' => 915],
            ['grupo' => 'E', 'altura_min' => 27, 'altura_max' => 27.5, 'valor_y' => 922],
            ['grupo' => 'E', 'altura_min' => 27.5, 'altura_max' => 28, 'valor_y' => 928],
            ['grupo' => 'E', 'altura_min' => 28, 'altura_max' => 28.5, 'valor_y' => 934],
            ['grupo' => 'E', 'altura_min' => 28.5, 'altura_max' => 29, 'valor_y' => 939],
            ['grupo' => 'E', 'altura_min' => 29, 'altura_max' => 29.5, 'valor_y' => 944],
            ['grupo' => 'E', 'altura_min' => 29.5, 'altura_max' => 30, 'valor_y' => 949],
            ['grupo' => 'E', 'altura_min' => 30, 'altura_max' => 30.5, 'valor_y' => 953],
            ['grupo' => 'E', 'altura_min' => 30.5, 'altura_max' => 31, 'valor_y' => 957],
            ['grupo' => 'E', 'altura_min' => 31, 'altura_max' => 31.5, 'valor_y' => 960],
            ['grupo' => 'E', 'altura_min' => 31.5, 'altura_max' => 32, 'valor_y' => 963],
            ['grupo' => 'E', 'altura_min' => 32, 'altura_max' => 32.5, 'valor_y' => 966],
            ['grupo' => 'E', 'altura_min' => 32.5, 'altura_max' => 33, 'valor_y' => 969],
            ['grupo' => 'E', 'altura_min' => 33, 'altura_max' => 33.5, 'valor_y' => 972],
            ['grupo' => 'E', 'altura_min' => 33.5, 'altura_max' => 34, 'valor_y' => 974],
            ['grupo' => 'E', 'altura_min' => 34, 'altura_max' => 34.5, 'valor_y' => 976],
            ['grupo' => 'E', 'altura_min' => 34.5, 'altura_max' => 35, 'valor_y' => 978],
            ['grupo' => 'E', 'altura_min' => 35, 'altura_max' => 35.5, 'valor_y' => 980],
            ['grupo' => 'E', 'altura_min' => 35.5, 'altura_max' => 36, 'valor_y' => 981],
            ['grupo' => 'E', 'altura_min' => 36, 'altura_max' => 36.5, 'valor_y' => 983],
            ['grupo' => 'E', 'altura_min' => 36.5, 'altura_max' => 37, 'valor_y' => 984],
            ['grupo' => 'E', 'altura_min' => 37, 'altura_max' => 37.5, 'valor_y' => 986],
            ['grupo' => 'E', 'altura_min' => 37.5, 'altura_max' => 38, 'valor_y' => 987],
            ['grupo' => 'E', 'altura_min' => 38, 'altura_max' => 38.5, 'valor_y' => 988],
            ['grupo' => 'E', 'altura_min' => 38.5, 'altura_max' => 39, 'valor_y' => 989],
            ['grupo' => 'E', 'altura_min' => 39, 'altura_max' => 39.5, 'valor_y' => 990],
            ['grupo' => 'E', 'altura_min' => 39.5, 'altura_max' => 40, 'valor_y' => 991],
            ['grupo' => 'E', 'altura_min' => 40, 'altura_max' => 40.5, 'valor_y' => 991],

            // Agrega más valores según sea necesario...
        ];


        DB::table('valores_y')->insert($valores_y);
    }
}
